TOOLTIP_ENCHANTS = {
  {"HP +100", "+100 Health"},
  {"Mana +150", "+150 Mana"},
  {"Armor +125", "+125 Armor"},
  {"Strength +8", "+8 Strength"},
  {"Agility +8", "+8 Agility"},
  {"Stamina +8", "+8 Stamina"},
  {"Intellect +8", "+8 Intellect"},
  {"Spirit +8", "+8 Spirit"},
  {"Dodge +1%", "+1% Dodge"},
  {"Stamina +16 and Armor +100", "+16 Stamina\n+100 Armor"},
  {"Healing +31 and 5 mana per 5 sec.", "+31 Healing Spells\n+5 mana every 5 sec."},
  {"Spell Damage +15 and +1% Spell Critical Strike", "+15 Spell Power\n+1% Spell Critical Strike"},
  {"Attack Power +26 and +1% Critical Strike", "+26 Attack Power\n+1% Critical Strike"},
  {"Healing and Spell Damage +8", "+8 Spell Power"},
  {"Attack Speed +1%", "+1% Attack Speed"},
  {"Healing and Spell Damage +18/Spell Hit +1%", "+18 Spell Power\n+1% Spell Hit"},
  {"Mana Regen +4/Stamina +10/Healing Spells +24", "+10 Stamina\n+4 mana every 5 sec\n+24 Healing Spells"},
  {"Healing and Spell Damage +18/Stamina +10", "+10 Stamina\n+18 Spell Power"},
  {"Intellect +10/Stamina +10/Healing Spells +24", "+10 Stamina\n+10 Intellect\n+24 Healing Spells"},
  {"Attack Power +28/Dodge +1%", "+28 Attack Power\n+1% Dodge"},
  {"Ranged Attack Power +24/Stamina +10/Hit +1%", "+10 Stamina\n+24 Ranged Attack Power\n+1% Hit"},
  {"Healing and Spell Damage +13/Intellect +15", "+15 Intellect\n+13 Spell Power"},
  {"Defense +7/Stamina +10/Healing Spells +24", "+10 Stamina\n+7 Defense\n/+24 Healing Spells"},
  {"Defense +7/Stamina +10/Block Value +15", "+10 Stamina\n+7 Defense\n+15 Block Value"},
  {"+18 Spell Damage and Healing", "+18 Spell Power"},
  {"Armor +10", "+10 Armor"},
  {"Armor +20", "+20 Armor"},
  {"Armor +30", "+30 Armor"},
  {"Armor +50", "+50 Armor"},
  {"Armor +70", "+70 Armor"},
  {"Reinforced Armor +8", "+8 Armor"},
  {"Reinforced Armor +16", "+16 Armor"},
  {"Reinforced Armor +24", "+24 Armor"},
  {"Reinforced Armor +32", "+32 Armor"},
  {"Reinforced Armor +40", "+40 Armor"},
  {"Agility +1", "+1 Agility"},
  {"Agility +3", "+3 Agility"},
  {"Subtlety"},
  {"Increased Stealth"},
  {"Health +5", "+5 Health"},
  {"Health +15", "+15 Health"},
  {"Health +25", "+25 Health"},
  {"Health +35", "+35 Health"},
  {"Health +50", "+50 Health"},
  {"Health +100", "+100 Health"},
  {"Mana +5", "+5 Mana"},
  {"Mana +30", "+30 Mana"},
  {"Mana +50", "+50 Mana"},
  {"Mana +65", "+65 Mana"},
  {"Mana +100", "+100 Mana"},
  {"Absorption (10)", "+10 Absorption"},
  {"Absorption (25)", "+25 Absorption"},
  {"All Stats +1", "+1 All Stats"},
  {"All Stats +2", "+2 All Stats"},
  {"All Stats +3", "+3 All Stats"},
  {"All Stats +4", "+4 All Stats"},
  {"Strength +1", "+1 Strength"},
  {"Strength +3", "+3 Strength"},
  {"Strength +5", "+5 Strength"},
  {"Strength +7", "+7 Strength"},
  {"Strength +9", "+9 Strength"},
  {"Strength +15", "+15 Strength"},
  {"Agility +1", "+1 Agility"},
  {"Agility +3", "+3 Agility"},
  {"Agility +5", "+5 Agility"},
  {"Agility +7", "+7 Agility"},
  {"Agility +15", "+15 Agility"},
  {"Stamina +1", "+1 Stamina"},
  {"Stamina +3", "+3 Stamina"},
  {"Stamina +5", "+5 Stamina"},
  {"Stamina +7", "+7 Stamina"},
  {"Stamina +9", "+9 Stamina"},
  {"Intellect +3", "+3 Intellect"},
  {"Intellect +5", "+5 Intellect"},
  {"Intellect +7", "+7 Intellect"},
  {"Spirit +1", "+1 Spirit"},
  {"Spirit +3", "+3 Spirit"},
  {"Spirit +5", "+5 Spirit"},
  {"Spirit +7", "+7 Spirit"},
  {"Spirit +9", "+9 Spirit"},
  {"Defense +1", "+1 Defense"},
  {"Defense +2", "+2 Defense"},
  {"Defense +3", "+3 Defense"},
  {"Healing Spells +24", "+24 Healing Spells"},
  {"Mana Regen 4 per 5 sec.", "+4 mana every 5 sec"},
  {"Fishing +2", "+2 Fishing"},
  {"Herbalism +2", "+2 Herbalism"},
  {"Herbalism +5", "+5 Herbalism"},
  {"Mining +2", "+2 Mining"},
  {"Mining +5", "+5 Mining"},
  {"Skinning +5", "+5 Skinning"},
  {"Minor Mount Speed Increase"},
  {"Minor Speed Increase"},
  {"Fishing +2", "+2 Fishing"},
  {"Fishing +2", "+2 Fishing"},
  {"Fishing +2", "+2 Fishing"},
  {"Threat +2%", "+2% Threat"},
  {"Fire Damage +20", "+20 Fire Spell Damage"},
  {"Frost Damage +20", "+20 Frost Spell Damage"},
  {"Shadow Damage +20", "+20 Shadow Spell Damage"},
  {"Healing Spells +30", "+30 Healing Spells"},
  {"Beastslaying +2", "+2 Beastslaying"},
  {"Beastslaying +6", "+6 Beastslaying"},
  {"Elemental Slayer +6", "+6 Elemental Slayer"},
  {"Demonslaying"},
  {"Weapon Damage +1", "+1 Weapon Damage"},
  {"Weapon Damage +2", "+2 Weapon Damage"},
  {"Weapon Damage +3", "+3 Weapon Damage"},
  {"Weapon Damage +4", "+4 Weapon Damage"},
  {"Weapon Damage +5", "+5 Weapon Damage"},
  {"Weapon Damage +7", "+7 Weapon Damage"},
  {"Weapon Damage +9", "+9 Weapon Damage"},
  {"Frost Spell Damage +7", "+7 Frost Spell Damage"},
  {"Icy Weapon"},
  {"Spell Damage +30", "+30 Spell Power"},
  {"Healing Spells +55", "+55 Healing Spells"},
  {"Weapon Chain - Immune Disarm"},
  {"Crusader"},
  {"Fiery Weapon"},
  {"Unholy Weapon"},
  {"Lifestealing"},
  {"Agility +25", "+25 Agility"},
  {"Spirit +3", "+3 Spirit"},
  {"Spirit +9", "+9 Spirit"},
  {"Spirit +20", "+20 Spirit"},
  {"Intellect +3", "+3 Intellect"},
  {"Intellect +9", "+9 Intellect"},
  {"Intellect +22", "+22 Intellect"},
  {"Blocking +2%", "+2% Block Chance"},
  {"Minor Mana Oil"},
  {"Lesser Mana Oil"},
  {"Brilliant Mana Oil"},
  {"Minor Wizard Oil"},
  {"Lesser Wizard Oil"},
  {"Wizard Oil"},
  {"Brilliant Wizard Oil"},
  {"Blessed Wizard Oil"},
  {"Shadow Oil"},
  {"Frost Oil"},
  {"Rough Weightstone"},
  {"Coarse Weightstone"},
  {"Heavy Weightstone"},
  {"Solid Weightstone"},
  {"Dense Weightstone"},
  {"Heavy Weightstone"},
  {"Heavy Weightstone"},
  {"Heavy Weightstone"},
  {"Rough Sharpening Stone"},
  {"Coarse Sharpening Stone"},
  {"Heavy Sharpening Stone"},
  {"Solid Sharpening Stone"},
  {"Dense Sharpening Stone"},
  {"Elemental Sharpening Stone"},
  {"Consecrated Sharpening Stone"},
  {"Instant Toxin"},
  {"Instant Poison"},
  {"Instant Poison II"},
  {"Instant Poison III"},
  {"Instant Poison IV"},
  {"Instant Poison V"},
  {"Instant Poison VI"},
  {"Deadly Poison"},
  {"Deadly Poison II"},
  {"Deadly Poison III"},
  {"Deadly Poison IV"},
  {"Deadly Poison V"},
  {"Mind-numbing Poison"},
  {"Mind-numbing Poison II"},
  {"Mind-numbing Poison III"},
  {"Crippling Poison"},
  {"Crippling Poison II"},
  {"Wound Poison"},
  {"Wound Poison II"},
  {"Wound Poison III"},
  {"Wound Poison IV"},
  {"Flametongue 1"},
  {"Flametongue 2"},
  {"Flametongue 3"},
  {"Flametongue 4"},
  {"Flametongue 5"},
  {"Flametongue 6"},
  {"Rockbiter 1"},
  {"Rockbiter 2"},
  {"Rockbiter 3"},
  {"Rockbiter 4"},
  {"Rockbiter 5"},
  {"Rockbiter 6"},
  {"Rockbiter 7"},
  {"Windfury 1"},
  {"Windfury 2"},
  {"Windfury 3"},
  {"Windfury 4"},
  {"Windfury"},
  {"Aquadynamic Fish Attractor"},
  {"Bright Baubles"},
  {"Flesh Eating Worm"},
  {"Nightcrawlers"},
  {"Aquadynamic Fish Lens"},
  {"Shiny Bauble"}
}

-- dont need fixing
TOOLTIP_ENCHANTS_GOODBOYS = {
  {"+5 Arcane Resistance"},
  {"+5 Fire Resistance"},
  {"+7 Fire Resistance"},
  {"+15 Fire Resistance"},
  {"+20 Fire Resistance"},
  {"+5 Nature Resistance"},
  {"+10 Nature Resistance"},
  {"+15 Nature Resistance"},
  {"+5 Frost Resistance"},
  {"+8 Frost Resistance"},
  {"+5 Shadow Resistance"},
  {"+10 Shadow Resistance"},
  {"+1 All Resistances"},
  {"+3 All Resistances"},
  {"+5 All Resistances"},
  {"+33 Healing Spells"},
  {"+30 Attack Power"},
}
